### ISSUE TITLE
Написать инструкцию для создания документации по проекту

### ISSUE THREAD

**Issue by DRMPN** [ITMO-NSS-team/open-source-ops#15]
Необходимо написать пошаговую инструкцию по составлению докуменатции для проектов с использованием readthedocs

**Comment by nicl-nno** [comment]
@DenisSidoren тут видимо нужно будет твоё участие.

По формату докстрингов предлагаю ориентироваться на гугловский.

**Comment by DenisSidoren** [comment]
@nicl-nno Хорошо, подумаю над этим. Пока что видится это как перечень шагов со ссылками на туториалы и комментариями из собственной практики
