### ISSUE TITLE
Создать кнопку-badge для перехода на gitlab-версию

### ISSUE THREAD

**Issue by nicl-nno** [ITMO-NSS-team/open-source-ops#35]
В связи с новостями вида https://habr.com/ru/news/t/722182/ хочется подстраховаться и добавить в наши репозитории кнопку для перехода к gitlab-версии (там где таковая есть). Чтобы даже public archive версия была связана с актуальным кодом.

Нужно подобрать подходящий badge и сделать пример использования (в rst и md).

**Comment by pacifikus** [comment]
Как насчет <img src="https://badgen.net/badge/gitlab/mirror/orange?icon=gitlab"/> ?

**Comment by andreygetmanov** [comment]
Ну и не вижу особого смысла создавать отдельный шаблон
Мне кажется, можно просто в шаблон readme добавить эти строчки:

|GitLab|_

.. |GitLab| image:: https://camo.githubusercontent.com/9bd7b8c5b418f1364e72110a83629772729b29e8f3393b6c86bff237a6b784f6/68747470733a2f2f62616467656e2e6e65742f62616467652f6769746c61622f6d6972726f722f6f72616e67653f69636f6e3d6769746c6162
.. _GitLab: https://gitlab.com/gitlab-org/gitlab
