### ISSUE TITLE
Open-source meetup №2 - сбор тем для выступлений (очных)

### ISSUE THREAD

**Issue by nicl-nno** [ITMO-NSS-team/open-source-ops#9]
Планируется провести второй митап в рамках КМУ.

"Секция посвящена реализации методов и моделей ИИ в рамках библиотек с открытым исходным кодом.  Мы принимаем доклады, посвященные:
·       Опыту создания конкретных open-source разработок;
·       Историям успехов и неудач, возникавших в ходе участия в OS-проектах.
·       "Лучшим практикам" в области создания открытого ПО в целом;
·       Анонсам своих научных проектов (в формате мини-презентации на 3-5 минут), открытых для сторонних участников.

Также в рамках секции планируется проведение неформальной дискуссии по различным аспектам открытого ПО."

Темы можно предлагать прямо тут - указывайте только при этом контакт для связи.

**Comment by andreygetmanov** [comment]
Рабочее название темы моей темы: 
ChatGPT и Copilot: как писать код без напряжения

**Comment by valer1435** [comment]
Рабочее название моей темы: 
Зачем студенту участвовать в open-source проектах?

**Comment by maypink** [comment]
Рабочее название моей темы:
Хакатоны как метод апробации ИИ фреймворков

**Comment by VKorzhuk** [comment]
Рабочее название темы:
Case-study: как собрать систему обработки медицинских данных на основе open source
